### ISSUE TITLE
Trees on guynmart_wood_13 do not match those on guynmart_wood_1 or guynmart_wood_8

### ISSUE THREAD

**Issue by Rijackson** [Rijackson/bugfix_0_7_4#3]

**Comment by NutAndor** [comment]
The whole Guynmart area has a problem with map matching. I remember, that we discussed if we'd change the worldmap to a version without gaps.
Although I'd prefer it, it would be a huge amount of work for the whole world - I wouldn't want to do it...
So I'll change the Guynmart maps to gap version now

**Comment by Rijackson** [comment]
Yeah. I would also prefer no gaps, The gaps sometimes make it impossible to line things up correctly in two directions. However, as you say, changing it would be a huge amount of work. I don't think most players even notice, so we should concentrate on other things.

Edit: by which I mean that we should make the maps match with a one tile gap, not that we should ignore the mismatch.

**Comment by NutAndor** [comment]
I fixed most of the alignment mismatches.
In some cases, where it is a forest, I didn't change it, because it would be to much change or not even possible.
Btw. There are places, that can't be entered, but should be nevertheless walkable, because some animals spawn there, just for show.
